version: "3.7"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: masker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  auth-server:
    env_file: .env
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: services/auth-server/Dockerfile

  alias-manager:
    env_file: .env
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: services/alias-manager/Dockerfile

  mail-exchanger:
    env_file: .env
    restart: always
    depends_on:
      - postgres
    ports:
      - 4000:3000
    build:
      context: .
      dockerfile: services/mail-exchanger/Dockerfile

  payment-handler:
    env_file: .env
    restart: always
    depends_on:
      - postgres
    ports:
      - 4001:3000
    build:
      context: .
      dockerfile: services/payment-handler/Dockerfile

  payment-manager:
    env_file: .env
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: services/auth-server/Dockerfile

  caddy:
    image: caddy:2.4.3-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    ports:
      - 5000:3000
      - 2019:2019

volumes:
  postgres-data:
  caddy-data:
    external: true
  caddy-config:
